# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 100
  # Genome build
  build: GRCh38

trimming:
  activate: True

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    A-vs-B:
      - A
      - B
  model: ~condition

params:
  cutadapt-pe: ""
  cutadapt-se: ""
  star: "--outSAMtype BAM Unsorted"